version: '3.8'

services:
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/app/bot"
    volumes:
      - .:/app/bot
    command: "python3 -m bot"
    restart: always
    env_file: .env

    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"